@baseUrl = http://localhost:5008

### Listar produtos

GET {{baseUrl}}/api/produtos
Accept: application/json

### Criar carrinho

# @name criarCarrinho
POST {{baseUrl}}/api/carrinhos
Accept: application/json

### Consultar carrinho criado

GET {{baseUrl}}/api/carrinhos/{{criarCarrinho.response.body.$.id}}
Accept: application/json

### Consultar carrinho inexistente

GET {{baseUrl}}/api/carrinhos/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
Accept: application/json

### Documento OpenAPI

GET {{baseUrl}}/openapi/v1.json
Accept: application/json